name: Crreate gitHub actions ci-cd pipeline
on:
  push:
    branches: [ "main" ]
jobs:
  deploy-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up aws Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-south-1

      - name: Set up python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pipenv
        run: pip install pipenv

      - name: Initialize environment
        run: |
          echo "python VERSION -> python3.11"
          echo "__Starting Lambda layer creation utility__"
          pipenv install

      - name: Generate requirements.txt
        run: pipenv requirements > requirements.txt

      - name: Clean up Old artifacts
        run: |
          rm -f *.zip
          rm -f *.tmp

      - name: Lint with flake8
        run: |
          echo "__ Linting the code with flake8 __"
          pip install flake8
          flake8 . #adjust path as needed

      - name: Build function zip
        run: |
          echo "__ zipping the main lambda code __"
          zip -gr ./$(basename $PWD).zip ./* -x "*^.*|$(basename $PWD).zip"

      - name: Update Lambda Function code
        run: |
          echo "__ Updating lambda function code in AWS __"
          aws lambda update-function-code \
            --function-name $(basename $PWD) \
            --zip-file fileb://$(basename $PWD).zip

      - name: Create zip for layer package
        run: |
          echo "__ zipping python libraries for the Lambda layer __"
          pipenv shell
          cd $VIRTUAL_ENV
          mkdir python
          cp -r lib python/
          zip -r9 ${GITHUB_WORKSPACE}/packages.zip python/
          rm -r $VIRTUAL_ENV/python

      - name: Publisg Lambda Layer
        run: |
          echo "__ Publishing new lambda layer version __"
          desc="$(grep -o '.*==.....' ${GITHUB_WORKSPACE}/requirements.txt)"
          aws lambda publish-layer-version \
            --layer-name $(basename $PWD) \
            --description "$desc" \
            --zip-file fileb://${GITHUB_WORKSPACE}/packages.zip \
            --compaible-runtimes python3.6 python3.11 \
            --compatible-architectures "arm64" "x86_64" > layer.tmp

      - name: Update Function Configuration with New Layer
        run: |
          echo "__ Updating function configuration to use the new layer __"
          cat layer.tmp | grep -o "arn.*$(basename $PWD):[0-9]*" > arn.tmp
          arn="$(cat arn.tmp)"
          aws lambda update-function-configuration \
            --function-name $(basename $PWD) \
            --layers "$arn"
      - name: Final Cleanup
        run: |
          rm -f *.zip
          rm -f *.tmp


          