name: Crreate gitHub actions ci-cd pipeline
on:
  push:
    branches: [ "main" ]
jobs:
  deploy-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up aws Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ap-south-1

      - name: Set up python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install pipenv
        run: pip install pipenv

      - name: Initialize environment
        run: |
          echo "python VERSION -> python3.11"
          echo "__Starting Lambda layer creation utility__"
          pipenv install

      - name: Generate requirements.txt
        run: pipenv requirements > requirements.txt

      - name: Clean up Old artifacts
        run: |
          rm -f *.zip
          rm -f *.tmp

      - name: Lint with flake8
        run: |
          echo "__ Linting the code with flake8 __"
          pip install flake8
          flake8 . #adjust path as needed

      - name: Build function zip
        run: |
          echo "__ zipping the main lambda code __"
          zip -gr ./$(basename $pwd).zip ./* -x "*^.*|$(basename $pwd).zip"

      - name: Update Lambda Function code
        run: |
          echo "__ Updating lambda function code in AWS __"
          aws lambda update-function-code \
            --function-name $(basename $pwd) \
            --zip-file fileb://$(basename $pwd).zip

      - name: Create zip for layer package
        run: |
          echo "__ zipping python libraries for the Lambda layer __"

          